// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package v1

import (
	"time"
)

type NewStream struct {
	Name     string `json:"name"`
	Username bool   `json:"username"`
}

type Stream struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Username  string    `json:"username"`
	Viewers   int       `json:"viewers"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
