server:
  http_listen_port: 3100
  grpc_listen_port: 9095
memberlist:
  join_members:
    - loki_reader:7946
    - loki_writer:7946

common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  ring:
    kvstore:
      store: memberlist

schema_config:
  configs:
    - from: 2022-02-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /tmp/loki

analytics:
  reporting_enabled: false
