server:
  http_listen_port: 3100
  grpc_listen_port: 9095
memberlist:
  join_members:
    - loki_reader:7946
    - loki_writer:7946

schema_config:
  configs:
    - from: 2022-02-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      endpoint: minioloki:9000
      insecure: true
      bucketnames: loki-data
      access_key_id: minio_access_key
      secret_access_key: minio_secret_key
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist

ruler:
  storage:
    s3:
      bucketnames: loki-ruler

analytics:
  reporting_enabled: false
