server:
  http_listen_port: 3100
memberlist:
  join_members:
    - loki_reader:7946
    - loki_writer:7946
schema_config:
  configs:
    - from: 2022-02-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    filesystem:
      chunks_directory: /data/chunks
      rules_directory: /data/rules
  ring:
    kvstore:
      store: memberlist
