server:
  host: 0.0.0.0
  port: 9091
  path: "auth"

authentication_backend:
  file:
    path: /data/users_database.yml

access_control:
  default_policy: deny
  rules:
   - domain: localhost
     policy: one_factor

session:
  domain: localhost

storage:
  local:
    path: /data/authelia.sqlite3

notifier:
  filesystem:
    filename: /data/notification.txt

log:
  level: debug
