version: "3.8"
services:
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    environment:
      AUTHELIA_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /secrets/SESSION_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/STORAGE_ENCRYPTION_KEY
    ports:
      - "9091:9091"
    volumes:
      - ./authelia/config:/config
      - ./authelia/secrets:/secrets
      - ./authelia/data:/data
