apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: ntjTOP1Vz
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
    editable: true
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: ZCYhas14z
    url: http://loki_reader:3100
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    editable: true
