// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/belo4ya/live-streaming-service/services/stream/internal/conf"
	"github.com/belo4ya/live-streaming-service/services/stream/internal/server"
	"github.com/belo4ya/live-streaming-service/services/stream/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, logger log.Logger) (*kratos.App, func(), error) {
	serviceService := service.NewService(logger)
	grpcServer := server.NewServer(confServer, serviceService)
	app := newApp(logger, grpcServer)
	return app, func() {
	}, nil
}
