// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package v1

import (
	"time"
)

type Message struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	ChannelID string    `json:"channelID"`
	UserID    string    `json:"userID"`
	Username  string    `json:"username"`
	Content   string    `json:"content"`
}

type NewMessage struct {
	ChannelID string `json:"channelID"`
	UserID    string `json:"userID"`
	Username  string `json:"username"`
	Content   string `json:"content"`
}
