global:
  scrape_interval: 15s

scrape_configs:
  - job_name: general
    scrape_interval: 60s
    static_configs:
      - targets: [ cadvisor:8080, node-exporter:9100 ]
  - job_name: caddy
    static_configs:
      - targets: [ caddy:2019 ]
  - job_name: minio-loki
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: [ minio-loki:9000 ]
